# Generated by Django 5.1.5 on 2025-01-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2025-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="test@test.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meetup",
            name="participants",
            field=models.ManyToManyField(
                blank=True, null=True, to="meetups.participant"
            ),
        ),
    ]
